title: <p align="center"> Mohammad Tasleem Arif </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="www.linkedin.com/in/mohammad-tasleem-arif">LinkedIn</a> |
  <a href="https://github.com/Arif1234/">GitHub</a>
  
  <br>   
  I'm working on Data Science, Machine learning & NLP related problems.
  <br>
  </p>



theme: jekyll-theme-minimal
